# Generated by Django 5.0.2 on 2024-02-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
