# Generated by Django 5.0.2 on 2024-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Otimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
