# Generated by Django 5.0.2 on 2024-03-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_emprestimo_avaliacao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dono_livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dono_livro', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
