# Generated by Django 5.0.2 on 2024-03-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_livro_dono_livro_cadastrado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='dono_livro',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dono_livro_atual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dono_livro_atual', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
