# Generated by Django 5.0.2 on 2024-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_emprestimo_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
